### ISSUE TITLE
TypeError: Object has no method 'readUInt32LE'

### ISSUE THREAD

**Issue by Esowteric** [eknkc/consistent#2]
Hi, I'm new to node.js and have consistent running in Windows fine in a DNS load balancing proxy which I've written. However, having just installed consistent 1.0.3 on a Raspberry Pi, I'm getting the error:

TypeError: Object [garbled]
[garbled] has no method 'readUInt32LE'
at Consistent._hash (.../consistent.js:136:56) ...

The line is:
return crypto.createHash('md5').update(val).digest().readUInt32LE(0);

npm -v = 1.1.4.

Being a newbie, I don't know if this is relevant, but my project uses dgram's buffer which also has a method readUInt32LE. I'd be grateful for any ideas.

With good wishes,
Eric T.

**Comment by eknkc** [comment]
Yes, it looks like the binaries had an issue with crypto module.
You can also try `murmurhash` hashing

``` js
var ring = consistent({hash: 'murmurhash', ...})
```

It works faster than the `md5` based implementation and provided as a pure javascript module. `md5` has a slightly better distribution though.
