### ISSUE TITLE
Count keys and key exists

### ISSUE THREAD

**Issue by Esowteric** [eknkc/consistent#3]
Hi again, a couple of additional functions that I've found useful are member_count and key_exists:

Consistent.prototype.member_count = function() {
  var members = Object.keys(this.members);
  return members.length;
}

Consistent.prototype.key_exists = function(key) {
  var exists = false;
  var members = Object.keys(this.members);
  var ex = members.indexOf(key);
  if (ex == -1) {
    exists = false;
    }
  else {
    exists = true;
    }
  return exists;
}

Thanks again for a great library,
Eric T.

**Comment by eknkc** [comment]
Thanks! Added `.exists(member)` and `.length` in 626e8966181d42356b05d32fad62901a65c27386
